"""zapidprint
Simple command line script for reading a pass batch file generated by the
zaputil Java program
"""

from passgen import PassGenerator

def zapidprint(in_file, out_dir, page_size, margin, qr_pixel_scale,
               text_pixel_scale, pass_dim, fit_width, fit_height):
    """
    Create printable sheets of passes as a set of images in the
    given directory
    """

    