"""zapidprint
Simple command line script for reading a pass batch file generated by the
zaputil Java program
"""

import os

from batchread import BatchReader
from passgen import PassGenerator


def zapidprint(in_file, out_dir, width, height):
    """
    Create printable sheets of passes as a set of images in the
    given directory
    """

    # Import the file
    batch = BatchReader(in_file)

    # Make a new pass generator
    passgen = PassGenerator(width=width, height=height)

    # Write a bunch of images to the output directory
    id_idx = 0
    for (message, code) in batch:

        save_path = os.path.join(out_dir, 'id_{:05d}.png'.format(id_idx))
        img = passgen.generate(message, code)
        img.save(save_path)
        id_idx += 1
